#!/usr/bin/env bash
set -euo pipefail
(
    exec bwrap \
     --bind / / \
     --proc /proc \
     --dev /dev \
     --unshare-all \
     --new-session \
     --seccomp 10 \
     10< /usr/local/bin/seccomp_default_filter.bpf \
     /usr/bin/xz "$@"
)
