#!/usr/bin/env bash
set -euo pipefail
(
    exec bwrap \
     --ro-bind /usr/bin /usr/bin \
     --ro-bind /usr/share /usr/share \
     --ro-bind /usr/lib /usr/lib \
     --symlink /usr/lib /lib \
     --ro-bind /usr/lib64 /usr/lib64 \
     --symlink /usr/lib64 /lib64 \
     --proc /proc \
     --dev /dev \
     --dev-bind /dev/dri /dev/dri \
     --bind /sys/dev /sys/dev \
     --bind /sys/devices /sys/devices \
     --ro-bind /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" \
     --ro-bind-try ~/.config/imv/ ~/.config/imv/ \
     --ro-bind-try "${@: -1}" "$(realpath "${@: -1}")" \
     --unshare-all \
     --new-session \
     /usr/bin/imv-wayland "$@"
)
