#!/usr/bin/env bash
set -euo pipefail
(
    exec bwrap \
     --ro-bind /usr/bin /usr/bin \
     --ro-bind /usr/share /usr/share \
     --ro-bind /usr/lib /usr/lib \
     --ro-bind /usr/lib64 /usr/lib64 \
     --symlink /usr/lib64 /lib64 \
     --symlink /usr/bin /bin \
     --proc /proc \
     --dev /dev \
     --tmpfs /tmp \
     --ro-bind /run/user/"$(id -u)"/wayland-0 /run/user/"$(id -u)"/wayland-0 \
     --ro-bind /etc /etc \
     --ro-bind /sys /sys \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --bind ~/.cache/fontconfig ~/.cache/fontconfig \
     --bind ~/.config/libreoffice ~/.config/libreoffice \
     --bind ~/Documents ~/Documents \
     --bind "${@: -1}" "${@: -1}" \
     --chdir ~/Documents \
     --unshare-all \
     --new-session \
     --seccomp 10 \
     10< /usr/local/bin/seccomp_default_filter.bpf \
     /usr/bin/libreoffice "$@"
)
