#!/usr/bin/env bash
set -euo pipefail
(
    exec bwrap \
     --ro-bind /usr/bin/vlc /usr/bin/vlc \
     --ro-bind /usr/share /usr/share \
     --ro-bind /usr/lib /usr/lib \
     --ro-bind /usr/lib64 /usr/lib64 \
     --symlink /usr/lib64 /lib64 \
     --symlink /usr/bin /bin \
     --proc /proc \
     --ro-bind /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" \
     --ro-bind-try /run/user/"$(id -u)"/pipewire-0 /run/user/"$(id -u)"/pipewire-0 \
     --ro-bind /etc /etc \
     --ro-bind-try ~/.config/vlc ~/.config/vlc \
     --ro-bind-try "${@: -1}" "${@: -1}" \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --unshare-user-try \
     --unshare-pid \
     --unshare-net \
     --unshare-uts \
     --unshare-cgroup-try \
     --new-session \
     --seccomp 10 \
     10< /usr/local/bin/seccomp_default_filter.bpf \
     /usr/bin/vlc "$@"
)

## requires qt5-wayland to run on wayland
##  wayland support in vlc is currently still under development
