#!/usr/bin/env bash
set -euo pipefail
(
    exec bwrap \
     --ro-bind /usr/bin/zathura-sandbox /usr/bin/zathura-sandbox \
     --ro-bind /usr/share /usr/share \
     --ro-bind /usr/lib /usr/lib \
     --symlink /usr/lib /lib \
     --ro-bind /usr/lib64 /usr/lib64 \
     --symlink /usr/lib64 /lib64 \
     --dir /var/empty \
     --proc /proc \
     --ro-bind /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" \
     --ro-bind /etc/fonts /etc/fonts \
     --bind-try ~/.local/share/zathura ~/.local/share/zathura \
     --ro-bind-try ~/.config/zathura ~/.config/zathura \
     --bind-try ~/.cache/fontconfig ~/.cache/fontconfig \
     --ro-bind-try "${@: -1}" "$(realpath "${@: -1}")" \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --unshare-all \
     --new-session \
     --seccomp 10 \
     10< /usr/local/bin/seccomp_default_filter.bpf \
     /usr/bin/zathura-sandbox "$@"
)

## zathura supports a native sandbox via seccomp and landlock in a separate zathura-sandbox binary
