#!/usr/bin/env bash
set -euo pipefail
(
    exec bwrap \
     --ro-bind /usr/bin/mupdf /usr/bin/mupdf \
     --ro-bind /usr/share /usr/share \
     --ro-bind /usr/lib /usr/lib \
     --ro-bind /lib /lib \
     --ro-bind /lib64 /lib64 \
     --ro-bind /bin /bin \
     --proc /proc \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     --ro-bind /etc/fonts /etc/fonts \
     --ro-bind ~/.Xauthority /home/jail/.Xauthority \
     --ro-bind "${@: -1}" /home/jail/"$(basename ${@: -1})" \
     --chdir /home/jail \
     --unsetenv MOZ_PLUGIN_PATH \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --unsetenv XDG_RUNTIME_DIR \
     --setenv SHELL /bin/false \
     --setenv HOME /home/jail \
     --setenv XAUTHORITY /home/jail/.Xauthority \
     --setenv USER nobody \
     --unshare-all \
     --new-session \
     --seccomp 10 \
     10< /usr/local/bin/seccomp_default_filter.bpf \
     /usr/bin/mupdf "$(basename ${@: -1})" &>/dev/null
)
